### ISSUE TITLE
coin-or/Rehearse support

### ISSUE THREAD

**Issue by GuillaumeDesforges** [ampl/coin#10]
Would you mind adding coin-or/Rehearse to your work ? Would be great !

Thanks
Guillaume

**Comment by fdabrandao** [comment]
This project is intended to provide CMake build support to generate executable binaries of COIN-OR solvers. Since Rehearse is not a solver, it was not included; It would be necessary to generate libraries as well instead of just executable binaries. Nevertheless, fell free to fork this project and do the integration yourself.

Best regards,
Filipe
